fifa<-function(a)
{
    d<-1:13
    library(XML)
    library(httr)
    for(i in 1:a)
    {
        url<-paste('https://fifarenderz.com/20/players?page=',i,'&scope=DESC&filter=rating&bigcards=false',sep='')
        urldata<-GET(url)
        data<-htmlTreeParse(urldata,useInternalNodes=T)
        Rating<-xpathSApply(data,"//span[@class='rating']",xmlValue)
        Position<-xpathSApply(data,"//span[@class='position']",xmlValue)
        Name<-xpathSApply(data,"//span[@class='name']",xmlValue)
        tpp<-cbind(Rating,Position,Name)
        names<-c("PAC/DIV","SHO/POS","PAS/HAN","DRI/REF","DEF/KIC","PHY")
        Val<-xpathSApply(data,"//span",xmlValue)
        loop2<-11
        stat2<-1:4
        names(stat2)<-c("Club","League","Country","Skillboost")
        len2<-(nrow(tpp)*200)
        while(loop2<=len2)
        {
            if(is.na(Val[loop2]))
                break;
            per2<-c(Val[loop2],Val[loop2+1],Val[loop2+2],Val[loop2+3])
            stat2<-rbind(stat2,per2)
            loop2<-loop2+19
        }
        stat2<-stat2[-1,]
        stat2<-stat2[1:(nrow(tpp)),]
        tpp<-cbind(tpp,stat2)
        aa<-xpathSApply(data,"//span[@class='stat-stat']",xmlValue)
        loop<-1
        stat<-1:6
        names(stat)<-names
        len<-nrow(tpp)
        len<-len*6
        while(loop<=len)
        {
            per<-c(aa[loop],aa[loop+1],aa[loop+2],aa[loop+3],aa[loop+4],aa[loop+5])
            stat<-rbind(stat,per)
            loop<-loop+6
        }
        stat<-stat[-1,]
        tpp<-cbind(tpp,stat)
        print(i)
        d<-rbind(d,tpp)
    }
    d<-d[-1,]
    return(d)
}
