install.packages("name_")
install.packages(c("name_","name_"))
BiocManager::install("name_")
devtools::install_github("author_/package_")
library(name_)
detach()
detach("package:name_", unload=TRUE)
library()
installed.packages()
old.packages()
update.packages()
update.packages("name_")
remove.packages()
remove.packages("name_")
version()
sessionInfo()
help()
help(package= "name_")
brbrowseVignettes()
browseVignettes("name_")